name: port_tracker
description: Port Tracker is an application made by Team Knikker, commisioned by YoFlow. The goal of the application is to track moving devices in the Port of Antwerp.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.2.0                  # For geolocation tracking
  flutter_screenutil: ^0.4.2          # For loging page
  google_maps_flutter: ^0.5.21+15     # For map page
  loading: ^1.0.2                     # For loading spinner
  sliding_up_panel: ^0.3.6            # For sliding up panel
  provider: ^4.0.2                    # For state management
  barcode_scan:                       # For barcode scanner


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
          style: roboto_regular
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: roboto_italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          style: roboto_bold
          
    - family:
      fonts:
        - asset: fonts/Monsterrat/Monsterrat-Regular.ttf
          style: monsterrat_regular
        - asset: fonts/Monsterrat/Monsterrat-Italic.ttf
          style: monsterrat_italic
        - asset: fonts/Monsterrat/Monsterrat-Bold.ttf
          style: monsterrat_bold